# Generated by Django 5.1.1 on 2024-12-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usuario_is_active_remove_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username']},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
