# Generated by Django 5.1.1 on 2024-12-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='token_created',
        ),
    ]
