# Generated by Django 5.1.1 on 2024-12-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usuario_token_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateField(blank=True, null=True),
        ),
    ]
