# Generated by Django 5.1.1 on 2024-12-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_usuario_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permission_type',
            field=models.IntegerField(default=3),
        ),
    ]
